name: Keep Awake

on:
  schedule:
    - cron: '0 */10 * * *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Keepalive commit
        run: git commit --allow-empty -m "Keepalive commit"

      - name: Push changes
        run: git push origin main